In [14]:
import xarray as xr
import numpy as np 

In [27]:
data_path = "C:/Users/345578/Documents/GitHub/Transfer_HPC/SR_justGrass.nc"

Fates_xr  = xr.open_dataset(data_path) 
Fates_xr.update({'fates_fire_SAV':[0,0,0,0,0]})

MergeError: unable to determine if these variables should be coordinates or not in the merged result: {'fates_fire_SAV'}

In [18]:
#Ages=Fates_xr.coords['fates_levage'].values
#Time=Fates_xr.indexes['time'].to_datetimeindex()
#FuelClass=Fates_xr.indexes['fates_levfuel'].values  
#Canopy=Fates_xr.indexes['fates_levcan'].values  
#nscls_bins = len(Fates_xr.variables['fates_levscls'])
#npfts = len(Fates_xr.variables['fates_levpft'])
#nage_bins = len(Fates_xr.variables['fates_levage'])
#print(Time)

In [19]:
for i in Fates_xr.keys():
    print(i)
    print(Fates_xr[i].attrs)
    
    print(np.array(Fates_xr[i]))

fates_hlm_pft_map
{'units': 'area fraction', 'long_name': 'In fixed biogeog mode, fraction of HLM area associated with each FATES PFT'}
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
fates_history_sizeclass_bin_edges
{'units': 'cm', 'long_name': 'Lower edges for DBH size class bins used in size-resolved cohort history output'}
[  0.   5.  10.  15.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
fates_history_ageclass_bin_edges
{'units': 'yr', 'long_name': 'Lower edges for age class bins used in age-resolved patch history output'}
[ 0.  1.  2.  5. 10. 20. 50.]
fates_litterclass_name
{'units': 'unitless - string', 'long_name': 'Name of the litter classes, for variables associated with dimension fates_litterclass'}
[b'twig                         